### ISSUE TITLE
User Story 18, Items Index Page Statistics

### ISSUE THREAD

**Issue by GDemps** [LHJE/monster_shop_2005#22]
As any kind of user on the system
When I visit the items index page ("/items")
I see an area with statistics:
- the top 5 most popular items by quantity purchased, plus the quantity bought
- the bottom 5 least popular items, plus the quantity bought

"Popularity" is determined by total quantity of that item ordered

**Comment by leahriffell** [comment]
Per team meeting: everyone will make their own US18 branch and try to work on tackling w/ Active Record. On Monday we will regroup and compare solutions. In the meantime, we can also continue working on other assigned stories. @priyapower @LHJE @GDemps
